### ISSUE TITLE
Проверьте мой курсовой проект. Но это далеко не финал.

### ISSUE THREAD

**Issue by POOSTOTEL** [POOSTOTEL/java-learning#33]
@IrishkA13

**Comment by IrishkA13** [comment]
@POOSTOTEL очень крутая работа! 
Комментариев много,  но не такие значительные) много восторга от твоей работы!
Хотелось бы видеть пул реквест - очень неудобно комментировать)

1) Можно   использовать  1   метод   вместо   4.  
printRequestForInputSearchPhrase   
printRequestForInputDate
printRequestForInputStatus  
printRequestForInputNumber 
Классно,  что используешь  статические методы,  так
как текст для вывода не константа, оно будет выводиться каждый раз.

2) Validator - хотелоось бы видеть exception (в том числе, потому что мы их проходили) и не видеть System.out.println внутри валидатора. Завтра пройдем веб, и вывод будет в формает html, отправляться пользователю через http - придется лезть и переписывать валидатор. Если он только бросает исключения, ничего не знает о консоли, он хороший класс, который только валадирует, не превышая свои полномочия. Наш консольный runner будет печатать в консоль, а подчклюим http - он уже по-своему будет обрабатывать ошибки.

3) private LocalDateTime editTime; //editionTime, чтобы было существительное, а не глагол
и чтобы все время называлось в одном стиле, можно переименовать creationTime вместо timeOfCreation

4) В классе ToDo - лучше без this, если у нас единственоое fileWithTaskList, то лучше меньше кода)
if (!this.fileWithTaskList.exists()) {

5) Вместо forEach лучше использовать findFirst, вернет Optional, и если таски с такимм номером нету, ошибка пользователю, что выбрал номер несуществующего таска и возврат в меню.
arrayList.stream()
         .filter(task -> task.number == taskNumber)
         .forEach(task -> ...);
		 
6) setFinishedStatus - также exception и ошибка пользователю про невалидный статус

7) deleteTask тоже можно найти task через стрим. 
Этот копи-пастный кусок кода с поиском по номеру таски хорошо бы вынести в private-метод.

8) как насчет toStringShortly, а лучше toStringBreifly вместо shortToString?)
или просто getBreifInfo?

9) printFilteredByFinishTime 
task.getCompletionTime().isAfter(time) возможен NullPointer, если completionTime null

10) не вижу, чтобы при вызове методов менялось editTime

11) deserializingListOfTasksFromFile - если файл пустой, то лучше бы сделать taskWithMaxTaskNumber.map(Task::getNumber).orEsle(0);  вместо taskWithMaxTaskNumber.get().number 
 Optional<Task> taskWithMaxTaskNumber = arrayList.stream()
                    .max(Comparator.comparingInt(task -> task.number));
Task.maxTaskNumber = taskWithMaxTaskNumber.get().number;

12) Хотелось бы после create, edit, delete делать сохранение в файл

13) Про пакеты: model - это классы, которые хранят состояние системы, то есть набор полей, которые записываются в файлы, базу данных.
Давай ValidationException поместим в отдельный package exception
ConsoleInfoPrinter - это тоже не модель, давай поместим в Service. 

14) Как насчет переименовать ToDo в ToDoList?
ToDo необходимо разделить на 2 независимых класса - один модель (хранит состояние, умеет добавлять, редактировать, удалять и т. д.). Второй класс - будет записывать в файл (а, в будущем, в xml и БД - уже можно создать интерфейс, помнишь?)
Было бы здорово, если бы ToDo не использоавл System.out.println - сегодня выводим на консоль, завтра по http или другим способом. Лучше, чтобы каждый метод возвращал список после применения stream, а уже в Runner вызывались все System.out.println
Вообще есть мысли выделить внутри ToDo класс ToDoService для всяких агрегацяи с листом, чтобы ToDoList умел только хранить, добавлять, удалять, возвращать stream-объектов. Ладно, давай пока оставим ToDoList

15) эти три методв копи-паст, поэтому могут вызывать private-метод, принимающий Predicate
printFilteredByStatus
printFilteredByFinishTime
searchTaskByName

16) В setFinishedStatus ты проставляешь Status.CANCELED статус

17) Не уверена, что на финальном этапе стоит в TodoListRunner создавать 5 тасок, если тебе удобно в начале - оставляй, но в финале лучше удалить.

18) TodoListRunner(строка 98) - switch case 8 - Status.valueOf и будет проще, без огрмоного swicth)

19) Для проверки, что пользователь вводит корректного типа данные, можно сделать private-методы - переиспользовать при создании и редактировании. 
Для всех сложных больших case в switch в TodoListRunner можно сделать private-метод.

20) Валидация есть в Task-констуркторе и Validator - должна быть в одном месте.
